export const protectedRoutes = [
  "/login",
  "/cart",
  "/wishlist",
  "/dashboard",
  "/dashboard/:page",
  "/dashboard/profile",
  "/dashboard/profile/change-password",
  "/dashboard/profile/change-status",
  "/dashboard/listing",
  "/dashboard/listing/:page",
  "/dashboard/sales-history",
  "/dashboard/purchase-history",
  "/messages",
  "/messages/:page",
  "/dashboard/admin",
  "/dashboard/admin/profile",
  "/dashboard/admin/profile/change-password",
  "/dashboard/admin/profile/change-status",
  "/dashboard/admin/:page",
  "/dashboard/admin/user-management",
  "/dashboard/admin/user-management/:page",
  "/dashboard/admin/listings",
  "/dashboard/admin/listings/:page",
];

export type userRoles = "user" | "admin" | "superAdmin";
